### ISSUE TITLE
Paths issue

### ISSUE THREAD

**Issue by crawfordlong** [MMarco94/linux-guides#2]
I've gotten Syncthing up and running using your very helpful guide. I'm having an issue when it comes to where files go. 

Let's say I map ~/Shared to /SharedData in the config. Using your default permissions (running as root in the container for now). 

If I share **FROM** another machine **TO** the Silverblue machine, it appears to sync, but I cannot find any files in the ~/Shared and it eventually throws an error that the path isn't found.

For example, if I have a new machine, I want to grab the syncthing share of my ~/Documents folder. So I connect to one of my nodes and, from any of them, share the Documents folder to the new Silverblue machine. I receive the notice that a share is inbound, but even if I try to set the destination to /SharedData/Documents with the goal of symlinking to ~/Documents later, it doesn't work. 

Thank you so much for documenting this process. I'm sure it's user error on my part.

**Comment by crawfordlong** [comment]
Hm, ok, I found the files. They're showing up in 

/var/home/$USER/.local/share/containers/storage/overlay/$ID/diff/$PATH (where $PATH = "SharedData" above)

I feel like I have the volume definition the wrong way around. I'm going to look at which order to define volumes in podman (i.e., container path vs. host path).

**Comment by MMarco94** [comment]
Can you share your Podman container definition (e.g. the command you used for creating the container, or the content of the systemd unit file)?

**Comment by MMarco94** [comment]
It's been a while. Closing this. 

If you have other issues, please feel free to open a new one
