### ISSUE TITLE
missing step: How to add new folders after the container has already been created

### ISSUE THREAD

**Issue by tazihad** [MMarco94/linux-guides#3]
Hi. Thanks for the guide. Have you figured out how to add new folder in already created container?

**Comment by MMarco94** [comment]
You probably need to run again the Podman command to create the container, and then update the systemd definition. I'll set a reminder to update the guide this weekend :)

**Comment by MMarco94** [comment]
Instructions added (better late than never I guess).

Sorry for the delay
